"""add_face_embedding_to_users

Revision ID: 3ff7cc37ac3c
Revises: 902a895cb23a
Create Date: 2026-05-27 11:14:33.668279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff7cc37ac3c'
down_revision: Union[str, None] = '902a895cb23a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('face_embedding', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'face_embedding')
    # ### end Alembic commands ###
