"""add device_tokens table for FCM push

Revision ID: 902a895cb23a
Revises: 005_drop_oauth_accounts
Create Date: 2026-05-26 20:35:14.115576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '902a895cb23a'
down_revision: Union[str, None] = '005_drop_oauth_accounts'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fcm_token', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_device_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_tokens'))
    )
    op.drop_index(op.f('ix_viewer_invitations_elderly_id'), table_name='viewer_invitations')
    op.drop_index(op.f('ix_viewer_invitations_status'), table_name='viewer_invitations')
    op.drop_index(op.f('ix_viewer_invitations_token'), table_name='viewer_invitations')
    op.drop_index(op.f('ix_viewer_invitations_viewer_id'), table_name='viewer_invitations')
    op.drop_table('viewer_invitations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewer_invitations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('elderly_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('invited_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('viewer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('accepted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['elderly_id'], ['elderly_profiles.id'], name=op.f('fk_viewer_invitations_elderly_id_elderly_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_viewer_invitations_invited_by_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], name=op.f('fk_viewer_invitations_viewer_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_viewer_invitations'))
    )
    op.create_index(op.f('ix_viewer_invitations_viewer_id'), 'viewer_invitations', ['viewer_id'], unique=False)
    op.create_index(op.f('ix_viewer_invitations_token'), 'viewer_invitations', ['token'], unique=True)
    op.create_index(op.f('ix_viewer_invitations_status'), 'viewer_invitations', ['status'], unique=False)
    op.create_index(op.f('ix_viewer_invitations_elderly_id'), 'viewer_invitations', ['elderly_id'], unique=False)
    op.drop_table('device_tokens')
    # ### end Alembic commands ###
