"""add google_id to users for Google OAuth

Revision ID: 4ca1ad02fd88
Revises: 902a895cb23a
Create Date: 2026-05-27 09:35:12.959661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca1ad02fd88'
down_revision: Union[str, None] = '902a895cb23a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(op.f('uq_users_google_id'), 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_google_id'), 'users', type_='unique')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
